
spring:
    rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest

#turbine:
#    aggregator:
#        clusterConfig: default
#    clusterNameExpression: new String("default")
#    appConfig: threeq-service-user,threeq-server-zuul
#    clusterNameExpression: 'default'
#    InstanceMonitor:
#        eventStream:
#            skipLineLogic: false

logging:
    level:
        root: DEBUG
        com.netflix.discovery: 'OFF'
        org.springframework.integration: INFO

