spring:
    rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest
opentracing:
    spring:
        cloud:
            websocket:
                enabled: false
            feign:
                enabled: false