version: "3.1"

services:
    rabbitmq:
        build:
            context: docker
            dockerfile: rabbitmq-Dockerfile
        ports:
            - 4369:4369
            - 5671:5671
            - 5672:5672
            - 25672:25672
    elasticsearch:
        build:
            context: docker
            dockerfile: es-Dockerfile
        ports:
            - 9200:9200
            - 9300:9300
    kibana:
        build:
            context: docker
            dockerfile: kibana-Dockerfile
        ports:
            - 5601:5601
        links:
            - elasticsearch
    grafana:
        build:
            context: docker
            dockerfile: grafana-Dockerfile
        ports:
            - 3000:3000
        links:
            - elasticsearch